apiVersion: v1
kind: Service
metadata:
  name: shopi-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: shopi-redis
  ports:
  - name: shopi-redis
    port: 6379
    targetPort: 6379
