FROM node:22-alpine

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm install
RUN npm i -g nodemon
EXPOSE 4001

CMD [ "npm", "run", "dev" ]
