apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: production
spec:
  storageClassName: mongo-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate

