apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shopi-mongo
  namespace: production 
spec:
  selector:
    matchLabels:
      app: shopi-mongo
  serviceName: shopi-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: shopi-mongo
    spec:
      containers:
      - name: shopi-mongo
        image: mongo:7-jammy
        ports:
        - containerPort: 27017
          name: shopi-mongo
        volumeMounts:
        - name: mongo-local-storage
          mountPath: /data/dn
      volumes:
      - name: mongo-local-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
