apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
spec:
  storageClassName: mysql-local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce