apiVersion: v1
kind: Service
metadata:
  name: shopi-queue
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: shopi-queue
  ports:
  - name: queue
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: mgmt
    port: 15672
    targetPort: 15672
    protocol: TCP
